/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnGeometryRouteImport } from './routes/learn/geometry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnGeometryRoute = LearnGeometryRouteImport.update({
  id: '/learn/geometry',
  path: '/learn/geometry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn/geometry': typeof LearnGeometryRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn/geometry': typeof LearnGeometryRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn/geometry': typeof LearnGeometryRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learn/geometry' | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn/geometry' | '/learn'
  id: '__root__' | '/' | '/learn/geometry' | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnGeometryRoute: typeof LearnGeometryRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/geometry': {
      id: '/learn/geometry'
      path: '/learn/geometry'
      fullPath: '/learn/geometry'
      preLoaderRoute: typeof LearnGeometryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnGeometryRoute: LearnGeometryRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
